import esbuild from 'esbuild'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

class CSSBundler {
    constructor(basePath) {
        this.basePath = basePath
        this.cssImports = new Map()
        this.cssContent = new Map()
        this.componentCSSMap = new Map() // Карта компонент -> CSS
    }

    // Находим все CSS файлы в проекте
    async findCSSFiles(dir) {
        const files = []

        async function scanDirectory(currentDir) {
            const entries = await fs.promises.readdir(currentDir, { withFileTypes: true })

            for (const entry of entries) {
                const fullPath = path.join(currentDir, entry.name)

                if (entry.isDirectory()) {
                    await scanDirectory(fullPath)
                } else if (entry.isFile() && path.extname(entry.name) === '.css') {
                    files.push(fullPath)
                }
            }
        }

        await scanDirectory(dir)
        return files
    }

    // Обрабатываем CSS файлы и создаем карту компонентов
    async processCSSFiles(cssFiles) {
        for (const filePath of cssFiles) {
            const content = await fs.promises.readFile(filePath, 'utf-8')
            const relativePath = path.relative(this.basePath, filePath)

            // Обрабатываем @import правила
            const processedContent = await this.processCSSImports(content, path.dirname(filePath))
            this.cssContent.set(relativePath, processedContent)

            // Определяем к какому компоненту относится CSS
            const componentName = this.extractComponentName(relativePath)
            if (componentName) {
                if (!this.componentCSSMap.has(componentName)) {
                    this.componentCSSMap.set(componentName, [])
                }
                this.componentCSSMap.get(componentName).push(relativePath)
            }
        }
    }

    // Извлекаем имя компонента из пути к CSS
    extractComponentName(cssPath) {
        const match = cssPath.match(/components\/([^\/]+)\/css\//)
        return match ? match[1] : null
    }

    // Обрабатываем @import в CSS
    async processCSSImports(content, baseDir) {
        const importRegex = /@import\s+(?:url\()?['"]([^'"]+)['"](?:\))?\s*;/g
        let processedContent = content

        let match
        while ((match = importRegex.exec(content)) !== null) {
            const importPath = match[1]
            const fullImportPath = path.resolve(baseDir, importPath)

            if (fs.existsSync(fullImportPath)) {
                const importedContent = await fs.promises.readFile(fullImportPath, 'utf-8')
                const nestedContent = await this.processCSSImports(importedContent, path.dirname(fullImportPath))
                processedContent = processedContent.replace(match[0], nestedContent)
            }
        }

        return processedContent
    }

    // Генерируем единый CSS бандл
    generateCSSBundle() {
        let bundle = '/* CSS Bundle - Generated by esbuild */\n'

        for (const [filePath, content] of this.cssContent) {
            bundle += `\n/* ${filePath} */\n`
            bundle += content
            bundle += '\n'
        }

        return bundle
    }

    // Создаем виртуальный модуль для CSS с поддержкой компонентов
    createCSSModule() {
        const cssBundle = this.generateCSSBundle()
        const cssPaths = Array.from(this.cssContent.keys())

        return `
      const cssContent = ${JSON.stringify(cssBundle)};
      const cssPaths = ${JSON.stringify(cssPaths)};
      const componentCSSMap = ${JSON.stringify(Object.fromEntries(this.componentCSSMap))};
      
      // Функция для получения CSS по пути
      export function getCSSByPath(filePath) {
        const normalizedPath = filePath.replace(/\\\\/g, '/');
        const entry = cssPaths.find(path => path.replace(/\\\\/g, '/').includes(normalizedPath));
        
        if (entry) {
          const startMarker = '/* ' + entry + ' */';
          const startIndex = cssContent.indexOf(startMarker) + startMarker.length;
          let endIndex = cssContent.length;
          
          // Ищем следующий маркер
          for (let i = cssPaths.indexOf(entry) + 1; i < cssPaths.length; i++) {
            const nextMarker = '/* ' + cssPaths[i] + ' */';
            const nextIndex = cssContent.indexOf(nextMarker);
            if (nextIndex !== -1) {
              endIndex = nextIndex;
              break;
            }
          }
          
          return cssContent.substring(startIndex, endIndex).trim();
        }
        return null;
      }
      
      // Получить CSS для компонента по имени
      export function getCSSForComponent(componentName) {
        const componentPaths = componentCSSMap[componentName];
        if (!componentPaths) return null;
        
        return componentPaths.map(path => getCSSByPath(path)).filter(Boolean).join('\\n');
      }
      
      // Получить весь CSS
      export function getAllCSS() {
        return cssContent;
      }
      
      // Вставить CSS в документ
      export function injectCSS() {
        if (typeof document !== 'undefined') {
          const style = document.createElement('style');
          style.textContent = cssContent;
          document.head.appendChild(style);
        }
      }
      
      // Получить список всех CSS путей
      export function getCSSPaths() {
        return cssPaths;
      }
      
      // Получить CSS для нескольких путей
      export function getMultipleCSS(paths) {
        return paths.map(path => getCSSByPath(path)).filter(Boolean).join('\\n');
      }
      
      // Получить карту компонентов
      export function getComponentCSSMap() {
        return componentCSSMap;
      }
      
      // Экспорт по умолчанию - весь CSS
      export default cssContent;
    `
    }
}

// Функция для сбора расширенной статистики сборки
export async function generateBuildStats(config, result, cssBundler, startTime) {
    const endTime = Date.now();
    const buildTime = endTime - startTime;

    // Собираем информацию о файлах
    const fileTypes = {
        css: { count: 0, totalSize: 0 },
        js: { count: 0, totalSize: 0 },
        mjs: { count: 0, totalSize: 0 },
        html: { count: 0, totalSize: 0 },
        other: { count: 0, totalSize: 0 }
    };

    // Анализируем CSS файлы - используем правильное свойство
    const cssFiles = cssBundler.cssFiles || [];
    cssFiles.forEach(filePath => {
        try {
            const stats = fs.statSync(filePath);
            fileTypes.css.count++;
            fileTypes.css.totalSize += stats.size;
        } catch (error) {
            console.warn(`Не удалось получить статистику для CSS файла: ${filePath}`);
        }
    });

    // Анализируем исходные файлы проекта
    function analyzeDirectory(dir) {
        try {
            const files = fs.readdirSync(dir, { withFileTypes: true });

            for (const file of files) {
                const fullPath = path.join(dir, file.name);

                if (file.isDirectory()) {
                    // Пропускаем node_modules и скрытые папки
                    if (!file.name.includes('node_modules') && !file.name.startsWith('.')) {
                        analyzeDirectory(fullPath);
                    }
                } else if (file.isFile()) {
                    try {
                        const stats = fs.statSync(fullPath);
                        const ext = path.extname(file.name).toLowerCase();

                        if (ext === '.js') {
                            fileTypes.js.count++;
                            fileTypes.js.totalSize += stats.size;
                        } else if (ext === '.mjs') {
                            fileTypes.mjs.count++;
                            fileTypes.mjs.totalSize += stats.size;
                        } else if (ext === '.html') {
                            fileTypes.html.count++;
                            fileTypes.html.totalSize += stats.size;
                        } else if (ext === '.css') {
                            // Уже учтены в CSS анализе
                        } else {
                            fileTypes.other.count++;
                            fileTypes.other.totalSize += stats.size;
                        }
                    } catch (error) {
                        console.warn(`Не удалось прочитать файл: ${fullPath}`);
                    }
                }
            }
        } catch (error) {
            console.warn(`Не удалось прочитать директорию: ${dir}`);
        }
    }

    try {
        analyzeDirectory(config.projectRoot);
    } catch (error) {
        console.warn(`Не удалось проанализировать корневую директорию: ${config.projectRoot}`);
    }

    // Форматируем размеры
    const formatSize = (bytes) => {
        if (bytes === 0) return '0 B';
        const k = 1024;
        const sizes = ['B', 'KB', 'MB', 'GB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
    };

    // Получаем размер выходного файла
    let outputSize = 'N/A';
    try {
        if (fs.existsSync(config.outfile)) {
            const stats = fs.statSync(config.outfile);
            outputSize = formatSize(stats.size);
        }
    } catch (error) {
        console.warn(`Не удалось получить размер выходного файла: ${config.outfile}`);
    }

    // Генерируем статистику
    const stats = {
        project: path.basename(config.projectRoot),
        buildTime: `${buildTime}ms (${(buildTime / 1000).toFixed(2)}s)`,
        outputFile: config.outfile,
        outputSize: outputSize,
        css: {
            files: cssFiles.length,
            components: cssBundler.componentCSSMap?.size || 0,
            totalSize: formatSize(fileTypes.css.totalSize)
        },
        sourceFiles: {
            js: fileTypes.js.count,
            mjs: fileTypes.mjs.count,
            html: fileTypes.html.count,
            other: fileTypes.other.count,
            total: fileTypes.js.count + fileTypes.mjs.count + fileTypes.html.count + fileTypes.other.count
        },
        timings: {
            start: new Date(startTime).toLocaleTimeString(),
            end: new Date(endTime).toLocaleTimeString(),
            duration: buildTime
        }
    };

    return stats;
}

// Функция для генерации README.md
export async function generateReadme(projectName, config, stats) {
    const readmePath = path.join(path.dirname(config.outfile), 'README.md');

    const readmeContent = `# ${projectName.toUpperCase()} Project Bundle

## 📦 Информация о сборке

- **Проект**: ${projectName}
- **Время сборки**: ${stats.buildTime}
- **Выходной файл**: ${path.basename(config.outfile)}
- **Размер бандла**: ${stats.outputSize}

## 🗂️ Статистика сборки

### Файлы CSS
- **CSS файлов**: ${stats.css.files}
- **Компонентов со стилями**: ${stats.css.components}
- **Общий размер CSS**: ${stats.css.totalSize}

### Исходные файлы
- **JavaScript файлов (.js)**: ${stats.sourceFiles.js}
- **ES модулей (.mjs)**: ${stats.sourceFiles.mjs}
- **HTML файлов**: ${stats.sourceFiles.html}
- **Прочих файлов**: ${stats.sourceFiles.other}
- **Всего файлов**: ${stats.sourceFiles.total}

## 🚀 Запуск проекта

### Вариант 1: Через сервер документации
\`\`\`bash
# Перейдите в директорию документации
cd /10/docs

# Запустите сервер
npm run dev

# Откройте в браузере
open http://localhost:6832/${projectName}
\`\`\`

### Вариант 2: Прямой запуск HTML файла
\`\`\`bash
# Откройте HTML файл непосредственно
open ./${projectName}/public/index.html

# Или через локальный сервер
npx serve ./${projectName}/public
\`\`\`

### Вариант 3: Через сборку
\`\`\`bash
# Сборка проекта
npm run build:${projectName}

# Сборка в режиме watch
npm run build:${projectName}:watch
\`\`\`

## 📁 Структура проекта

\`\`\`
${projectName}/
├── public/
│   ├── index.html          # Основной HTML файл
│   └── index.bundle.mjs    # Собранный бандл
├── src/
│   ├── components/         # Компоненты приложения
│   ├── base/              # Базовые классы
│   └── index.mjs          # Точка входа
└── ...
\`\`\`

## 🔧 Доступные скрипты

- \`npm run build:${projectName}\` - однократная сборка
- \`npm run build:${projectName}:watch\` - сборка с отслеживанием изменений
- \`npm run dev\` - запуск сервера разработки

## ⏱️ Временные метки сборки

- **Начало**: ${stats.timings.start}
- **Завершение**: ${stats.timings.end}
- **Длительность**: ${stats.timings.duration}ms

---

*Собрано автоматически ${new Date().toLocaleString()}*
`;

    try {
        await fs.promises.writeFile(readmePath, readmeContent, 'utf-8');
        console.log(`📖 README.md сгенерирован: ${readmePath}`);
        return true;
    } catch (error) {
        console.error('❌ Ошибка генерации README.md:', error);
        return false;
    }
}

// Основная функция сборки
export async function buildProject(config) {
    const {
        entryPoint,
        outfile,
        projectRoot,
        watch = false
    } = config

    console.log(`Starting build for: ${entryPoint}`)
    console.log(`Project root: ${projectRoot}`)
    console.log(`Output: ${outfile}`)
    console.log(`Watch mode: ${watch}`)

    const cssBundler = new CSSBundler(projectRoot)
    const startTime = Date.now()

    // Функция для перезагрузки CSS
    const reloadCSS = async () => {
        try {
            const cssFiles = await cssBundler.findCSSFiles(projectRoot)
            console.log(`🔄 Reloading ${cssFiles.length} CSS files`)
            await cssBundler.processCSSFiles(cssFiles)
            return true
        } catch (error) {
            console.error('❌ CSS reload failed:', error)
            return false
        }
    }

    try {
        // Находим и обрабатываем все CSS файлы
        const cssFiles = await cssBundler.findCSSFiles(projectRoot)
        console.log(`Found ${cssFiles.length} CSS files`)
        await cssBundler.processCSSFiles(cssFiles)

        // Конфигурация esbuild
        const buildConfig = {
            entryPoints: [entryPoint],
            bundle: true,
            sourcemap: true,
            format: 'esm',
            target: 'chrome114',
            platform: 'browser',
            outfile,
            keepNames: true,
            metafile: true, // Добавляем метафайл для статистики
            define: {
                global: 'window'
            },
            plugins: [
                {
                    name: 'css-bundler',
                    setup(build) {
                        // Виртуальный модуль для CSS
                        build.onResolve({ filter: /^virtual:css$/ }, args => {
                            return { path: 'virtual:css', namespace: 'virtual-css' }
                        })

                        build.onLoad({ filter: /^virtual:css$/, namespace: 'virtual-css' }, () => {
                            return {
                                contents: cssBundler.createCSSModule(),
                                loader: 'js'
                            }
                        })

                        // Обработка CSS импортов в JS - теперь загружаем из бандла
                        build.onLoad({ filter: /\.css$/ }, async (args) => {
                            try {
                                const relativePath = path.relative(projectRoot, args.path)
                                const componentName = cssBundler.extractComponentName(relativePath)

                                return {
                                    contents: `
                    import { getCSSByPath, getCSSForComponent } from 'virtual:css';
                    
                    const cssContent = getCSSByPath('${relativePath}') || '';
                    const componentCSS = ${componentName ? `getCSSForComponent('${componentName}')` : 'null'};
                    
                    export const cssContent = cssContent;
                    export const componentCSS = componentCSS;
                    export const cssPath = '${relativePath}';
                    export const componentName = '${componentName}';
                    export default cssContent;
                  `,
                                    loader: 'js'
                                }
                            } catch (error) {
                                console.error(`Error processing CSS file ${args.path}:`, error)
                                return {
                                    contents: `export default ''; export const cssContent = ''; export const cssPath = '';`,
                                    loader: 'js'
                                }
                            }
                        })
                    }
                }
            ]
        }

        let result;

        if (watch) {
            // Для watch mode используем context
            const context = await esbuild.context(buildConfig)

            // Функция для пересборки с обновленными CSS
            const rebuildWithCSS = async () => {
                await reloadCSS()
                try {
                    await context.rebuild()
                    console.log('✅ Build updated with latest CSS')
                } catch (error) {
                    console.error('❌ Rebuild failed:', error)
                }
            }

            // Отслеживаем изменения CSS файлов
            const cssWatchers = new Map()

            const setupCSSWatchers = async () => {
                const cssFiles = await cssBundler.findCSSFiles(projectRoot)

                // Очищаем старые вотчеры
                for (const [filePath, watcher] of cssWatchers) {
                    watcher.close()
                    cssWatchers.delete(filePath)
                }

                // Создаем новые вотчеры для CSS файлов
                for (const filePath of cssFiles) {
                    try {
                        const watcher = fs.watch(filePath, async (eventType) => {
                            if (eventType === 'change') {
                                console.log(`🎨 CSS changed: ${path.relative(projectRoot, filePath)}`)
                                await rebuildWithCSS()
                            }
                        })
                        cssWatchers.set(filePath, watcher)
                    } catch (error) {
                        console.warn(`⚠️ Cannot watch CSS file: ${filePath}`)
                    }
                }
            }

            // Настраиваем вотчеры при старте
            await setupCSSWatchers()

            // Также отслеживаем появление новых CSS файлов
            const cssDirWatcher = fs.watch(projectRoot, { recursive: true }, async (eventType, filename) => {
                if (filename && filename.endsWith('.css')) {
                    console.log(`📁 CSS file ${eventType}: ${filename}`)
                    await setupCSSWatchers()
                    await rebuildWithCSS()
                }
            })

            console.log(`👀 Watching for changes in ${projectRoot}...`)
            console.log(`🎨 CSS files watching: ${cssWatchers.size} files`)

            // Запускаем вотчер esbuild
            await context.watch()

            // Обработка graceful shutdown
            const cleanup = async () => {
                console.log('\n🧹 Cleaning up watchers...')

                // Закрываем CSS вотчеры
                for (const [filePath, watcher] of cssWatchers) {
                    watcher.close()
                }
                cssWatchers.clear()

                // Закрываем директорный вотчер
                cssDirWatcher.close()

                // Закрываем контекст esbuild
                await context.dispose()

                console.log('👋 All watchers stopped')
                process.exit(0)
            }

            process.on('SIGINT', cleanup)
            process.on('SIGTERM', cleanup)

            return context
        } else {
            // Обычная сборка
            result = await esbuild.build(buildConfig)

            // Генерируем статистику
            const stats = await generateBuildStats(config, result, {
                cssFiles: cssFiles,
                componentCSSMap: cssBundler.componentCSSMap
            }, startTime)

            // Выводим красивую статистику
            console.log(`\n📊 СТАТИСТИКА СБОРКИ ${path.basename(projectRoot).toUpperCase()}`)
            console.log(`═`.repeat(50))
            console.log(`🏁 Время сборки: ${stats.buildTime}`)
            console.log(`📦 Выходной файл: ${stats.outputFile}`)
            console.log(`📏 Размер бандла: ${stats.outputSize}`)
            console.log(``)
            console.log(`🎨 CSS файлы: ${stats.css.files} (${stats.css.totalSize})`)
            console.log(`🧩 Компоненты: ${stats.css.components}`)
            console.log(``)
            console.log(`📁 Исходные файлы:`)
            console.log(`   ├── JavaScript: ${stats.sourceFiles.js}`)
            console.log(`   ├── ES модули: ${stats.sourceFiles.mjs}`)
            console.log(`   ├── HTML: ${stats.sourceFiles.html}`)
            console.log(`   ├── Прочие: ${stats.sourceFiles.other}`)
            console.log(`   └── Всего: ${stats.sourceFiles.total}`)
            console.log(``)
            console.log(`⏰ Временные метки:`)
            console.log(`   ├── Начало: ${stats.timings.start}`)
            console.log(`   ├── Конец: ${stats.timings.end}`)
            console.log(`   └── Длительность: ${stats.timings.duration}ms`)
            console.log(`═`.repeat(50))

            // Генерируем README
            const projectName = path.basename(projectRoot);
            await generateReadme(projectName, config, stats)

            console.log(`✅ Build completed: ${outfile}`)
            return result
        }
    } catch (error) {
        console.error('❌ Build failed:', error)
        throw error
    }
}

// Утилита для создания конфига проекта
export function createProjectConfig(projectName, baseDir = __dirname) {
    const projects = {
        chat: {
            entryPoint: './chat/src/index.mjs',
            outfile: './chat/public/index.bundle.mjs',
            projectRoot: path.join(baseDir, 'chat/src')
        },
        youtube: {
            entryPoint: './youtube/public/index.mjs',
            outfile: './youtube/public/index.bundle.mjs',
            projectRoot: path.join(baseDir, 'youtube/src')
        },
        database: {
            entryPoint: './database/public/index.mjs',
            outfile: './database/public/index.bundle.mjs',
            projectRoot: path.join(baseDir, 'database/src')
        },
        wysiwyg: {
            entryPoint: './wysiwyg/public/index.mjs',
            outfile: './wysiwyg/public/index.bundle.mjs',
            projectRoot: path.join(baseDir, 'wysiwyg/src')
        },
        guss: {
            entryPoint: './packages/frontend/src/index.mjs',
            outfile: path.join(baseDir, './packages/public/index.bundle.mjs'),
            projectRoot: path.join(baseDir, './packages/frontend/src')
        }
    }

    return projects[projectName]
}